-- =============================================
-- Table: Master Payroll Configuration
-- Defines a reusable and versionable set of concepts for payrolls.
-- Only one configuration is 'active' at a time (not soft-deleted).
-- =============================================
CREATE TABLE app.tbl_payroll_configuration (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    public_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    code NVARCHAR(50) NOT NULL, -- Generated by backend, e.g., CONF_PLANILLA_YYYYMMDD
    description NVARCHAR(255) NULL,

    created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    created_by NVARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME2 NULL,
    updated_by NVARCHAR(100) NULL,
    deleted_at DATETIME2 NULL,
    deleted_by NVARCHAR(100) NULL
);
GO

-- Unique index for public_id, considering soft delete
CREATE UNIQUE NONCLUSTERED INDEX UQ_payroll_config_public_id_active
    ON app.tbl_payroll_configuration(public_id)
    WHERE deleted_at IS NULL;
GO

-- Unique index for code, considering soft delete
CREATE UNIQUE NONCLUSTERED INDEX UQ_payroll_config_code_active
    ON app.tbl_payroll_configuration(code)
    WHERE deleted_at IS NULL;
GO

-- =============================================
-- Table: Payroll Configuration Concepts
-- Join table for Master Payroll Configuration and Concepts (N:N relationship).
-- Stores concepts associated with a master configuration, including optional override values.
-- =============================================
CREATE TABLE app.tbl_payroll_configuration_concepts (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    public_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), -- ¡Añadido aquí!
    payroll_configuration_id BIGINT NOT NULL,
    concept_id SMALLINT NOT NULL,
    value DECIMAL(10,2) NULL, -- Override value for this concept within this configuration

    created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    created_by NVARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME2 NULL,
    updated_by NVARCHAR(100) NULL,
    deleted_at DATETIME2 NULL,
    deleted_by NVARCHAR(100) NULL,

    CONSTRAINT FK_payroll_config_concepts_config
        FOREIGN KEY (payroll_configuration_id)
        REFERENCES app.tbl_payroll_configuration(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,

    CONSTRAINT FK_payroll_config_concepts_concept
        FOREIGN KEY (concept_id)
        REFERENCES app.tbl_concepts(id)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);
GO

-- Unique index to prevent duplicate concepts within a configuration, considering soft delete
CREATE UNIQUE NONCLUSTERED INDEX UQ_payroll_config_concepts_active
    ON app.tbl_payroll_configuration_concepts(payroll_configuration_id, concept_id)
    WHERE deleted_at IS NULL;
GO

-- Index for quick lookup by concept
CREATE NONCLUSTERED INDEX IX_payroll_config_concepts_concept
    ON app.tbl_payroll_configuration_concepts(concept_id)
    WHERE deleted_at IS NULL;
GO

-- =============================================
-- Table: Payroll Concept Assignment (Snapshot for a specific Payroll)
-- This is the former tbl_payroll_configuration, now renamed and repurposed.
-- Stores the actual concepts assigned to a specific PayrollEntity at the time of its creation/calculation.
-- =============================================
CREATE TABLE app.tbl_payroll_concept_assignment (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    payroll_id BIGINT NOT NULL,
    concept_id SMALLINT NOT NULL,
    value DECIMAL(10,2) NULL, -- Snapshot value for this concept in this specific payroll

    created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    created_by NVARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    updated_at DATETIME2 NULL,
    updated_by NVARCHAR(100) NULL,
    deleted_at DATETIME2 NULL,
    deleted_by NVARCHAR(100) NULL,

    CONSTRAINT FK_payroll_concept_assignment_payroll
        FOREIGN KEY (payroll_id)
        REFERENCES app.tbl_payrolls(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,

    CONSTRAINT FK_payroll_concept_assignment_concept
        FOREIGN KEY (concept_id)
        REFERENCES app.tbl_concepts(id)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);
GO

-- Unique index to prevent duplicate concepts within a payroll, considering soft delete
CREATE UNIQUE NONCLUSTERED INDEX UQ_payroll_concept_assignment_active
    ON app.tbl_payroll_concept_assignment(payroll_id, concept_id)
    WHERE deleted_at IS NULL;
GO

-- Index for quick lookup by concept
CREATE NONCLUSTERED INDEX IX_payroll_concept_assignment_concept
    ON app.tbl_payroll_concept_assignment(concept_id)
    WHERE deleted_at IS NULL;
GO
