-- =============================================
-- Spring Batch Metadata Tables for SQL Server
-- Schema: app
-- =============================================

-- Crear secuencias primero (necesarias para las tablas)
IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name = 'BATCH_STEP_EXECUTION_SEQ' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE SEQUENCE app.BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CYCLE;
END
GO

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name = 'BATCH_JOB_EXECUTION_SEQ' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE SEQUENCE app.BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CYCLE;
END
GO

IF NOT EXISTS (SELECT * FROM sys.sequences WHERE name = 'BATCH_JOB_SEQ' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE SEQUENCE app.BATCH_JOB_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CYCLE;
END
GO

-- BATCH_JOB_INSTANCE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_JOB_INSTANCE' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE TABLE app.BATCH_JOB_INSTANCE (
        JOB_INSTANCE_ID BIGINT PRIMARY KEY,
        VERSION BIGINT,
        JOB_NAME VARCHAR(100) NOT NULL,
        JOB_KEY VARCHAR(32) NOT NULL,
        CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
    );
END
GO

-- BATCH_JOB_EXECUTION
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_JOB_EXECUTION' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE TABLE app.BATCH_JOB_EXECUTION (
        JOB_EXECUTION_ID BIGINT PRIMARY KEY,
        VERSION BIGINT,
        JOB_INSTANCE_ID BIGINT NOT NULL,
        CREATE_TIME DATETIME2 NOT NULL,
        START_TIME DATETIME2 DEFAULT NULL,
        END_TIME DATETIME2 DEFAULT NULL,
        STATUS VARCHAR(10),
        EXIT_CODE VARCHAR(2500),
        EXIT_MESSAGE VARCHAR(2500),
        LAST_UPDATED DATETIME2,
        CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
            REFERENCES app.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
    );
END
GO

-- BATCH_JOB_EXECUTION_PARAMS
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_JOB_EXECUTION_PARAMS' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE TABLE app.BATCH_JOB_EXECUTION_PARAMS (
        JOB_EXECUTION_ID BIGINT NOT NULL,
        PARAMETER_NAME VARCHAR(100) NOT NULL,
        PARAMETER_TYPE VARCHAR(100) NOT NULL,
        PARAMETER_VALUE VARCHAR(2500),
        IDENTIFYING CHAR(1) NOT NULL,
        CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES app.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
    );
END
GO

-- BATCH_STEP_EXECUTION
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_STEP_EXECUTION' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE TABLE app.BATCH_STEP_EXECUTION (
        STEP_EXECUTION_ID BIGINT PRIMARY KEY,
        VERSION BIGINT NOT NULL,
        STEP_NAME VARCHAR(100) NOT NULL,
        JOB_EXECUTION_ID BIGINT NOT NULL,
        CREATE_TIME DATETIME2 NOT NULL,
        START_TIME DATETIME2 DEFAULT NULL,
        END_TIME DATETIME2 DEFAULT NULL,
        STATUS VARCHAR(10),
        COMMIT_COUNT BIGINT,
        READ_COUNT BIGINT,
        FILTER_COUNT BIGINT,
        WRITE_COUNT BIGINT,
        READ_SKIP_COUNT BIGINT,
        WRITE_SKIP_COUNT BIGINT,
        PROCESS_SKIP_COUNT BIGINT,
        ROLLBACK_COUNT BIGINT,
        EXIT_CODE VARCHAR(2500),
        EXIT_MESSAGE VARCHAR(2500),
        LAST_UPDATED DATETIME2,
        CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES app.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
    );
END
GO

-- BATCH_STEP_EXECUTION_CONTEXT
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_STEP_EXECUTION_CONTEXT' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE TABLE app.BATCH_STEP_EXECUTION_CONTEXT (
        STEP_EXECUTION_ID BIGINT PRIMARY KEY,
        SHORT_CONTEXT VARCHAR(2500) NOT NULL,
        SERIALIZED_CONTEXT NVARCHAR(MAX),
        CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
            REFERENCES app.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
    );
END
GO

-- BATCH_JOB_EXECUTION_CONTEXT
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'BATCH_JOB_EXECUTION_CONTEXT' AND schema_id = SCHEMA_ID('app'))
BEGIN
    CREATE TABLE app.BATCH_JOB_EXECUTION_CONTEXT (
        JOB_EXECUTION_ID BIGINT PRIMARY KEY,
        SHORT_CONTEXT VARCHAR(2500) NOT NULL,
        SERIALIZED_CONTEXT NVARCHAR(MAX),
        CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES app.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
    );
END
GO

