package com.agropay.core.shared.constant;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum VariablesEnum {

    NOMBRE_EMPRESA("NOMBRE_EMPRESA"),
    RUC_EMPRESA("RUC_EMPRESA"),
    DOMICILIO_EMPRESA("DOMICILIO_EMPRESA"),
    REPRESENTANTE_LEGAL("REPRESENTANTE_LEGAL"),
    NOMBRE_COMPLETO_TRABAJADOR("NOMBRE_COMPLETO_TRABAJADOR"),
    DNI_TRABAJADOR("DNI_TRABAJADOR"),
    DOMICILIO_TRABAJADOR("DOMICILIO_TRABAJADOR"),
    NACIONALIDAD_TRABAJADOR("NACIONALIDAD_TRABAJADOR"),
    FECHA_NACIMIENTO_TRABAJADOR("FECHA_NACIMIENTO_TRABAJADOR"),
    CARGO_TRABAJADOR("CARGO_TRABAJADOR"),
    FECHA_FIRMA_CONTRATO("FECHA_FIRMA_CONTRATO"),
    FECHA_INICIO_CONTRATO("FECHA_INICIO_CONTRATO"),
    FECHA_FIN_CONTRATO("FECHA_FIN_CONTRATO"),
    DURACION_MESES("DURACION_MESES"),
    HORAS_DIARIAS("HORAS_DIARIAS"),
    DIAS_SEMANALES("DIAS_SEMANALES"),
    SALARIO_BASE("SALARIO_BASE"),
    TARIFA_HORA("TARIFA_HORA"),
    RECARGO_HORAS_EXTRAS("RECARGO_HORAS_EXTRAS"),
    RECARGO_FERIADOS("RECARGO_FERIADOS"),
    BONO_NOCTURNO("BONO_NOCTURNO"),
    DESCUENTO_RENTA("DESCUENTO_RENTA"),
    DESCUENTO_ESSALUD("DESCUENTO_ESSALUD"),
    DESCUENTO_PENSIONES("DESCUENTO_PENSIONES"),
    DIAS_VACACIONES("DIAS_VACACIONES"),
    LIMITE_ANTICIPOS("LIMITE_ANTICIPOS"),
    TIPO_CULTIVO("TIPO_CULTIVO"),
    UBICACION_PREDIO("UBICACION_PREDIO"),

    NUEVO_SALARIO("NUEVO_SALARIO"),

    NUEVA_FECHA_FIN("NUEVA_FECHA_FIN");

    private final String code;
}
